feign:
  oauth2:
    enabled: true
    load-balanced: true
spring:
  application:
    name: aeochaincontract
  cloud:
    loadbalancer:
      nacos:
        enabled: true
  liquibase:
    change-log: 'classpath:/db/changelog/changelog-master.xml'
  datasource:
    url: 'jdbc:h2:./test;FILE_LOCK=FS'
camunda:
  bpm:
    database:
      schema-update: false